name: CI in Release Branch

on:
  push:
    branches: [ release* ]
  pull_request:
    branches: [ release* ]
      
jobs:
  gitPullAndRestartPm2:
    runs-on: ubuntu-22.04
    steps:
    - name: git pull and restart pm2 instance
    - shell: bash
    - run: |
        cd /var/mycloud9x-back
        git pull
        npm install
        pm2 restart 0
    
