name: CI in Release Branch

on:
  push:
    branches: [ release* ]
  pull_request:
    branches: [ release* ]
      
jobs:
  gitPullAndRestartPm2:
    runs-on: ubuntu-22.04
    steps:
    - uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: | 
          cd /var/mycloud9x-back
          git pull
          npm install
          pm2 restart 0   
